# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='height',
        ),
        migrations.AddField(
            model_name='userdata',
            name='heightFeet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='heightInches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile',
            field=models.CharField(default='http://cdn3.denofgeek.us/sites/denofgeekus/files/scarlett_johansson.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='goals',
            field=models.CharField(choices=[('bulking', 'bulking'), ('slimming', 'slimming'), ('fitness', 'fitness')], max_length=10),
        ),
    ]
