# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20161113_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='intro',
            field=models.TextField(default='Hi'),
        ),
    ]
