# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20161113_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default='Pittsburgh', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.CharField(default='Carnegie Mellon University', max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='state',
            field=models.CharField(default='PA', max_length=100),
        ),
    ]
