# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20161113_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='goals',
            field=models.CharField(choices=[('bulking', 'bulking'), ('slimming', 'slimming'), ('fitness', 'fitness')], default='fitness', max_length=10),
        ),
    ]
